version: '2'
services:
    dependency-service:
        image: "mongo:4.0.2"
        ports:
            - "27017:27017"
    main-service:
        environment:
            - ENV_FILE=.deploy/.envs/test.env
        build:
            context: ..
            dockerfile: .deploy/Dockerfile
        ports:
            - "5000:5000"
        volumes:
            - ..:/app
        depends_on:
            - storage
        network_mode: host