version: '2'
services:
    service-api-prod:
        restart: always
        environment:
            - ENV_FILE=.deploy/.envs/prod.env
        build:
            context: ..
            dockerfile: .deploy/Dockerfile
        ports:
            - "5001:5001"
        volumes:
            - ..:/app
