version: '2'
services:
    dependency-service:
        image: "mongo:4.0.2"
        ports:
            - "27017:27017"
    main-service:
        environment:
            - ENV_FILE=.deploy/.envs/full.env
        build:
            context: ..
            dockerfile: .deploy/Dockerfile
        depends_on:
            - dependency-service
        network_mode: host
