version: '2'
services:
    tests:
        build:
            args:
                - ENV_FILE=.deploy/.envs/test.env
            context: ..
            dockerfile: .deploy/Dockerfile.test
        expose:
            - "5000"
        volumes:
            - ..:/app
        network_mode: host
